# -*- coding: utf-8 -*-
"""parkinsons_disease_detection_system.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lrkYEmD9hrSblvzKKzfW_mfe96UFK_4X

**IMPORTING IMPORTANT LIBRARIES FOR MODEL**
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn import svm
from sklearn.metrics import accuracy_score
import seaborn as sns
import matplotlib.pyplot as plt

"""**DATA  ACQUISITION AND ANALYSIS**"""

# loading data
parkinsions_data = pd.read_csv('/content/Parkinsson disease.csv')

parkinsions_data.head()

parkinsions_data.shape

"""**STATASTICAL MEASUREMENTS (Mean,Standard deviation, Minimum,Maximum ,etc)**"""

parkinsions_data.describe()

parkinsions_data.info()

# CHECKING FOR NOT NULL VALUES IN DATA
parkinsions_data.isnull().sum()

# calssification value counts
parkinsions_data['status'].value_counts()

#featuring the data based on target values
parkinsions_data.drop(columns=["name"]).groupby('status').mean()

"""**DATA PREPROSSING **

* SEPARATING THE FEATURES AND TRAGET COLUMNS
"""

X= parkinsions_data.drop(columns=['status','name'],axis=1)     # dropping columns --> axis =1
Y= parkinsions_data['status']

print(X)
print(Y)

"""**GRAPHICAL ANALYSIS **"""

# distribution of key voice features

features = [
    "MDVP:Fo(Hz)",
    "MDVP:Fhi(Hz)",
    "MDVP:Flo(Hz)",
    "HNR",
    "NHR",
    "spread1",
    "spread2",
    "PPE"
]

for feature in features:

    plt.figure(figsize=(6,4))

    sns.histplot(parkinsions_data[feature], kde=True)

    plt.title(f"Distribution of {feature}")

    plt.show()

important_features = [
    "MDVP:Fo(Hz)",
    "HNR",
    "NHR",
    "spread1",
    "PPE"
]

for feature in important_features:

    plt.figure(figsize=(6,4))

    sns.boxplot(x="status", y=feature, data=parkinsions_data)

    plt.title(f"{feature} vs Parkinson Status")

    plt.show()

plt.figure(figsize=(14,10))

parkinsions_data= parkinsions_data.drop(columns=["name"], axis=1)

corr = parkinsions_data.corr()


sns.heatmap(corr, cmap="coolwarm", annot=False)

plt.title("Feature Correlation Heatmap")

plt.show()



# red ->  strong correlation
# white-> weak correlation
# blue -> negative correlation

"""**spliting the data into target and features**"""

X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.2, random_state=2)
print(X.shape,Y.shape,X_test.shape,Y_test.shape)

#data standadisation
scaler = StandardScaler()

scaler.fit(X_train)

X_train=scaler.transform(X_train)
X_test=scaler.transform(X_test)

print(X_train)

"""**MODE TRAINING **

**----> training the data with different classification models *
"""

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

models = {
    "Logistic":LogisticRegression(),
    "RandomForest":RandomForestClassifier(),
    "SVM":SVC()
}

for name,model in models.items():

    model.fit(X_train,Y_train)
    pred = model.predict(X_test)

    acc = accuracy_score(Y_test,pred)

    print(name,acc*100)

"""SUPPROT VECTOR MACHINE MODEL"""

model = svm.SVC(kernel='rbf')

# training the svm model with training data
model.fit(X_train,Y_train)

"""model evaluation"""

# accuracy on training data
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(Y_train,X_train_prediction)

print('Accuracy score of training data:',training_data_accuracy*100)

X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(Y_test,X_test_prediction)

print('Accuracy score of test data:',test_data_accuracy)

from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC

param_grid = {
    'C':[0.1,1,10,100],
    'gamma':[1,0.1,0.01,0.001],
    'kernel':['rbf']
}

grid = GridSearchCV(SVC(),param_grid,refit=True)
grid.fit(X_train,Y_train)

print(grid.best_params_)

best_model = SVC(C=100, gamma=0.1, kernel='rbf')

best_model.fit(X_train, Y_train)

from sklearn.metrics import accuracy_score

X_test_prediction = best_model.predict(X_test)

test_accuracy = accuracy_score(Y_test, X_test_prediction)

print("Final Model Accuracy:", test_accuracy*100)

from sklearn.metrics import classification_report

print(classification_report(Y_test, X_test_prediction))

"""CONFUSION MATRICS"""

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

cm = confusion_matrix(Y_test, X_test_prediction)

sns.heatmap(cm, annot=True, fmt='d')
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()